name: Document Publish
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      
jobs:
  document-publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.title == 'chore":" version packages'
    steps:
      - name: Checkout ğŸ””
        uses: actions/checkout@v4
      - name: Node Setup ğŸ””
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Link ğŸ”¨
        run: yarn
      - name: packages build ğŸ”¨
        run: yarn build
      - name: prepare ğŸ”¨
        run: yarn prepare:docs
      - name: document build ğŸ”¨
        run: yarn build:docs
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          folder: ./docs/build

