name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ””
        uses: actions/checkout@v4
      - run: corepack enable
      - name: Node Setup ğŸ””
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: install ğŸ”¨
        run: yarn install --frozen-lockfile
      - name: build ğŸ”¨
        run: lerna run build
      - name: eslint ğŸš€
        run: yarn eslint packages
      - name: typecheck ğŸš€
        run: yarn typecheck
      - name: testing ğŸš€
        run: yarn test
      - name: document build ğŸ”¨
        run: yarn build:docs