name: Release
on:
  push:
    branches:
      - main
jobs:
  packages-release:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    steps:
      - name: Checkout ğŸ””
        uses: actions/checkout@v4
      - run: corepack enable
      - name: Node Setup ğŸ””
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: install ğŸ”¨
        run: yarn install --immutable
      - name: build ğŸ”¨
        run: lerna run build
      - name: eslint ğŸš€
        run: yarn eslint packages
      - name: typecheck ğŸš€
        run: yarn typecheck
      - name: testing ğŸš€
        run: yarn test
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          title: 'chore: version packages'
          commit: 'chore: version packages'
          version: yarn changeset:version
          publish: yarn changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
